##########欠费按时长分阶统计##########
欠费按时长分阶统计_费用时段="xpath==//span[@id='time']"
欠费按时长分阶统计_费用时段_开始="xpath==//tr[1]/td[@role='gridcell' and @class='ant-calendar-cell'][1]"
欠费按时长分阶统计_管理区="xpath==//div[@id='regionIds']"
欠费按时长分阶统计_选择管理区="xpath==//body/div[3]//ul/li[1]"
欠费按时长分阶统计_收费项目="xpath==//div[@id='chargeItemTypeIds']"
欠费按时长分阶统计_选择收费项目="xpath==//body/div[4]//ul/li[1]"
欠费按时长分阶统计_搜索="xpath==//button/span[text()='搜 索']/.."
欠费按时长分阶统计_重置="xpath==//button/span[text()='重 置']/.."
欠费按时长分阶统计_导出="xpath==//button/span[text()='导出Excel']/.."
欠费按时长分阶统计_表格="xpath==//table"
##########欠费按金额分阶统计##########
欠费按金额分阶统计_费用时段="xpath==//span[@id='time']"
欠费按金额分阶统计_费用时段_开始="xpath==//div[@class='ant-calendar-range-part ant-calendar-range-left']//tr[1]/td[1]"
欠费按金额分阶统计_费用时段_结束="xpath==//div[@class='ant-calendar-range-part ant-calendar-range-right']//tr[last()]/td[last()]"
欠费按金额分阶统计_管理区="xpath==//div[@id='regionIds']"
欠费按金额分阶统计_选择管理区="xpath==//body/div[3]//ul/li[1]"
欠费按金额分阶统计_收费项目="xpath==//div[@id='chargeItemTypeIds']"
欠费按金额分阶统计_选择收费项目="xpath==//body/div[4]//ul/li[1]"
欠费按金额分阶统计_楼宇停车场="xpath==//div[@id='organizationItemIds']"
欠费按金额分阶统计_选择楼宇停车场="xpath==//body/div[5]//ul/li[1]"
欠费按金额分阶统计_搜索="xpath==//form/div[1]//div/button[1]"
欠费按金额分阶统计_重置="xpath==//form/div[1]//div/button[2]"
欠费按金额分阶统计_导出="xpath==//form/parent::div/preceding-sibling::div/button"
欠费按金额分阶统计_表格="xpath==//table"